/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Tanel' at '20/09/17 14:18' with Gradle 2.14.1
 *
 * @author Tanel, @date 20/09/17 14:18
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
